### ISSUE TITLE
Quick Test

### ISSUE THREAD

**Issue by wasteland540** [enkidevs/commit#37]
Hey everybody,

i don't know where i have to put this issue exactly, so feel free to move it :)

I got two little bugs in the last days, when i take the quick test:
<a href="http://www.directupload.net/file/d/4577/f3kpiiae_jpg.htm" target="_blank"><img src="http://fs5.directupload.net/images/161222/temp/f3kpiiae.jpg" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>
<a href="http://www.directupload.net/file/d/4577/j7mklec9_jpg.htm" target="_blank"><img src="http://fs5.directupload.net/images/161222/temp/j7mklec9.jpg" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>
<a href="http://www.directupload.net/file/d/4577/lb3l7w9s_jpg.htm" target="_blank"><img src="http://fs5.directupload.net/images/161222/temp/lb3l7w9s.jpg" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

P.S: I really love your work, so keep it going!

**Comment by mathieudutour** [comment]
to be clear, the bug is the `NaN` and the `undefined` in the answers?

**Comment by wasteland540** [comment]
the bug is, i gave the right answers and the app is telling me i'm not right. But when i look at the right answers there is no different.

**Comment by mathieudutour** [comment]
@Loopiezlol

**Comment by loopiezlol** [comment]
Hey @wasteland540 
Firstly, I'd like to thank you for reporting this bug. User feedback is just a great way of continuously improve our content!

The reason behind the bug was that those insights have in their Revision Question multiple identical answers, but with different indexes.

However, I have updated the questions and their answers as to avoid this confusion.
